# Generated by Django 5.2.13 on 2026-05-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmstu_lab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankrequest",
            name="client",
        ),
        migrations.AddField(
            model_name="bankrequest",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="ФИО клиента"
            ),
        ),
        migrations.AddField(
            model_name="bankrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Операционист",
            ),
        ),
    ]
