# Generated by Django 5.2.13 on 2026-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bmstu_lab",
            "0002_remove_bankrequest_client_bankrequest_client_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankservice",
            name="price",
        ),
        migrations.AddField(
            model_name="bankserviceinrequest",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Комиссия за услугу",
            ),
        ),
    ]
