# Generated by Django 4.2 on 2026-04-05 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bmstu_lab", "0002_order_productinorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("DELETED", "Удалён"),
                            ("FORMED", "Сформирован"),
                            ("COMPLETED", "Завершён"),
                            ("REJECTED", "Отклонён"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "formed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата формирования"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "total_cost",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Стоимость обслуживания"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bank_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="managed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название услуги"),
                ),
                (
                    "rate",
                    models.CharField(max_length=20, verbose_name="Ставка/процент"),
                ),
                ("amount", models.CharField(max_length=50, verbose_name="Сумма/лимит")),
                ("term", models.CharField(max_length=50, verbose_name="Срок")),
                (
                    "balance_account",
                    models.CharField(max_length=5, verbose_name="Балансовый счёт"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Изображение (ключ в Minio)",
                    ),
                ),
                (
                    "video",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Видео (ключ в Minio)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankServiceInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        max_length=20, verbose_name="Банковский счёт клиента"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bmstu_lab.bankrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bmstu_lab.bankservice",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "unique_together": {("request", "service")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="productinorder",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productinorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="productinorder",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductInOrder",
        ),
    ]
