# Generated by Django 5.2.13 on 2026-05-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bmstu_lab", "0003_remove_bankservice_price_bankserviceinrequest_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankserviceinrequest",
            old_name="cost",
            new_name="service_cost",
        ),
    ]
