# Generated by Django 4.2 on 2026-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmstu_lab", "0003_bankrequest_bankservice_bankserviceinrequest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankrequest",
            name="client",
        ),
        migrations.RemoveField(
            model_name="bankserviceinrequest",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="bankserviceinrequest",
            name="quantity",
        ),
        migrations.AddField(
            model_name="bankrequest",
            name="client_name",
            field=models.CharField(
                default="Клиент по умолчанию",
                max_length=150,
                verbose_name="ФИО клиента",
            ),
        ),
    ]
