# Generated by Django 4.2 on 2026-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmstu_lab", "0004_remove_bankrequest_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankservice",
            name="is_active",
        ),
        migrations.AddField(
            model_name="bankservice",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Флаг мягкого удаления"
            ),
        ),
    ]
