# Generated by Django 4.2 on 2026-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmstu_lab", "0005_remove_bankservice_is_active_bankservice_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrequest",
            name="total_cost",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Стоимость обслуживания",
            ),
        ),
        migrations.AlterField(
            model_name="bankserviceinrequest",
            name="bank_account",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Банковский счёт клиента",
            ),
        ),
    ]
