-- Adminer 5.4.2 PostgreSQL 14.22 dump

DROP TABLE IF EXISTS "bmstu_lab_bankservice";
CREATE TABLE "public"."bmstu_lab_bankservice" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(100) NOT NULL,
    "rate" character varying(20) NOT NULL,
    "amount" character varying(50) NOT NULL,
    "term" character varying(50) NOT NULL,
    "balance_account" character varying(5) NOT NULL,
    "description" text NOT NULL,
    "image" character varying(100),
    "video" character varying(100),
    "is_active" boolean NOT NULL,
    CONSTRAINT "bmstu_lab_bankservice_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "bmstu_lab_bankservice" ("id", "name", "rate", "amount", "term", "balance_account", "description", "image", "video", "is_active") VALUES
(1,	'Кредит для бизнеса',	'от 16%',	'до 300 млн руб',	'до 5 лет',	'40701',	'Кредит на покупку оборудования, пополнение оборотных средств или модернизацию производства',	'credity_KB.png',	'credit.mp4',	'1'),
(2,	'Расчетный счет для бизнеса',	'0 руб обслуживание',	'без ограничений',	'постоянно',	'40702',	'Открытие онлайн, бесплатные переводы внутри банка, персональный менеджер',	'diploma.jpg',	'Video cash.mp4',	'1'),
(3,	'Кредитная карта',	'от 3%',	'до 1 млн руб',	'льготный период 120 дней',	'40801',	'Кэшбэк до 5%, бесплатное обслуживание при тратах от 5 000 ₽/мес.',	'credit_card.jpg',	'credit_card.mp4',	'1'),
(4,	'Депозит',	'до 15%',	'от 500 тыс руб',	'от 3 месяцев',	'40703',	'Гибкие условия, пополнение и частичное снятие',	'deposit.webp',	'deposit.mp4',	'1'),
(5,	'Эквайринг',	'от 1,5%',	'без ограничений',	'постоянно',	'40704',	'Приём карт, оплата по QR-коду, онлайн-касса в подарок',	'acquiring.jpg',	'acquaring.mp4',	'1');

-- 2026-04-07 17:44:36 UTC
