-- Adminer 5.4.2 PostgreSQL 14.22 dump

DROP TABLE IF EXISTS "bmstu_lab_bankserviceinrequest";
CREATE TABLE "public"."bmstu_lab_bankserviceinrequest" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "quantity" integer NOT NULL,
    "comment" character varying(255) NOT NULL,
    "bank_account" character varying(20) NOT NULL,
    "request_id" bigint NOT NULL,
    "service_id" bigint NOT NULL,
    CONSTRAINT "bmstu_lab_bankserviceinrequest_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "bmstu_lab_bankserviceinrequest_quantity_check" CHECK (((quantity >= 0)))
)
WITH (oids = false);

CREATE UNIQUE INDEX bmstu_lab_bankserviceinr_request_id_service_id_a4a7ed51_uniq ON public.bmstu_lab_bankserviceinrequest USING btree (request_id, service_id);

CREATE INDEX bmstu_lab_bankserviceinrequest_request_id_f3fea6d1 ON public.bmstu_lab_bankserviceinrequest USING btree (request_id);

CREATE INDEX bmstu_lab_bankserviceinrequest_service_id_5e5d116e ON public.bmstu_lab_bankserviceinrequest USING btree (service_id);

INSERT INTO "bmstu_lab_bankserviceinrequest" ("id", "quantity", "comment", "bank_account", "request_id", "service_id") VALUES
(1,	1,	'',	'40802810600000005678',	1,	1),
(2,	1,	'',	'40802810600000005678',	2,	1),
(3,	1,	'',	'40802810600000005678',	2,	2),
(5,	1,	'',	'40802810600000005678',	4,	1),
(6,	1,	'',	'40802810600000005678',	4,	2),
(7,	1,	'',	'40802810600000005678',	5,	1),
(8,	3,	'',	'40802810600000005678',	6,	5),
(4,	1,	'Новый комментарий',	'40802810600000005678',	3,	1),
(9,	1,	'',	'40802810600000005678',	7,	1);

ALTER TABLE ONLY "public"."bmstu_lab_bankserviceinrequest" ADD CONSTRAINT "bmstu_lab_bankservic_request_id_f3fea6d1_fk_bmstu_lab" FOREIGN KEY (request_id) REFERENCES bmstu_lab_bankrequest(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY "public"."bmstu_lab_bankserviceinrequest" ADD CONSTRAINT "bmstu_lab_bankservic_service_id_5e5d116e_fk_bmstu_lab" FOREIGN KEY (service_id) REFERENCES bmstu_lab_bankservice(id) DEFERRABLE INITIALLY DEFERRED;

-- 2026-04-07 17:44:44 UTC
