-- Adminer 5.4.2 PostgreSQL 14.22 dump

DROP TABLE IF EXISTS "bmstu_lab_bankrequest";
CREATE TABLE "public"."bmstu_lab_bankrequest" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "status" character varying(10) NOT NULL,
    "created_at" timestamptz NOT NULL,
    "formed_at" timestamptz,
    "completed_at" timestamptz,
    "total_cost" character varying(50) NOT NULL,
    "client_id" integer NOT NULL,
    "manager_id" integer,
    CONSTRAINT "bmstu_lab_bankrequest_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX bmstu_lab_bankrequest_client_id_909c47ee ON public.bmstu_lab_bankrequest USING btree (client_id);

CREATE INDEX bmstu_lab_bankrequest_manager_id_67e14e51 ON public.bmstu_lab_bankrequest USING btree (manager_id);

INSERT INTO "bmstu_lab_bankrequest" ("id", "status", "created_at", "formed_at", "completed_at", "total_cost", "client_id", "manager_id") VALUES
(1,	'DELETED',	'2026-04-05 13:25:42.111753+00',	NULL,	NULL,	'',	1,	NULL),
(2,	'DELETED',	'2026-04-05 13:37:41.3857+00',	NULL,	NULL,	'',	1,	NULL),
(3,	'DELETED',	'2026-04-05 13:46:50.064282+00',	NULL,	NULL,	'',	1,	NULL),
(4,	'DELETED',	'2026-04-05 14:08:57.99766+00',	NULL,	NULL,	'',	1,	NULL),
(5,	'DELETED',	'2026-04-05 18:50:16.126054+00',	NULL,	NULL,	'',	1,	NULL),
(6,	'DELETED',	'2026-04-05 18:51:08.953642+00',	NULL,	NULL,	'15000',	1,	NULL),
(7,	'DRAFT',	'2026-04-06 19:10:10.578431+00',	NULL,	NULL,	'',	1,	NULL);

ALTER TABLE ONLY "public"."bmstu_lab_bankrequest" ADD CONSTRAINT "bmstu_lab_bankrequest_client_id_909c47ee_fk_auth_user_id" FOREIGN KEY (client_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY "public"."bmstu_lab_bankrequest" ADD CONSTRAINT "bmstu_lab_bankrequest_manager_id_67e14e51_fk_auth_user_id" FOREIGN KEY (manager_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

-- 2026-04-07 17:44:28 UTC
